---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallpaper-deployer
  namespace: wallpaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wallpaper-deployer
  namespace: wallpaper
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wallpaper-deployer
  namespace: wallpaper
subjects:
  - kind: ServiceAccount
    name: wallpaper-deployer
    namespace: wallpaper
roleRef:
  kind: Role
  name: wallpaper-deployer
  apiGroup: rbac.authorization.k8s.io
